fail_fast: true
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v1.1.2
    hooks: 
      - id: go-fmt
      - id: go-vet-mod
      - id: golangci-lint-mod
        args: ["--allow-parallel-runners"]
      - id: go-build-repo-mod
      - id: go-mod-tidy
      - id: go-mod-tidy-repo

