name: Publish package in go-pkg

on:
  push:
    branches: [develop]

jobs:

  Release-go-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
          WITH_V: true
          VERBOSE: true

      - name: Publish go-pkg
        run: |
          echo ${{ steps.bump.outputs.new_tag }}
          echo ${{ steps.bump.outputs.tag }}
          echo ${{ steps.bump.outputs.part }}
          GOPROXY=proxy.golang.org go list -m github.com/wednesday-solutions/negt@{{ steps.bump.outputs.new_tag }}
