name: Publish package in go-pkg

on:
  push:
    branches: [develop]

jobs:
  Release-go-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
          WITH_V: true
          VERBOSE: true

      - name: Get commit messages
        id: commit-message
        run: |
          commit_msg=$(git show-branch --no-name HEAD)
          echo "commit_msg=$commit_msg" >> $GITHUB_OUTPUT
          echo $commit_msg

      - name: Create release note
        id: release-note
        run: |
          NOTE="New Version"
          if [[ ${{ steps.commit-message.outputs.commit_msg }} == 'feat'* ]]; then
            NOTE="New Features"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'fix'* ]]; then
            NOTE="Bug Fixes"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'chore'* ]]; then
            NOTE="Changes to build process or aux tools"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'revert'* ]]; then
            NOTE="Revert Commits"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'build'* ]]; then
            NOTE="Build"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'docs'* ]]; then
            NOTE="Documentation"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'perf'* ]]; then
            NOTE="Performance Enhancements"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'refactor'* ]]; then
            NOTE="Refactored"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'style'* ]]; then
            NOTE="Changed Style"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'temp'* ]]; then
            NOTE="Temporary Commit"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'test'* ]]; then
            NOTE="Added Tests"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'ci'* ]]; then
            NOTE="Changes to CI config"
          elif [[ ${{ steps.commit-message.outputs.commit_msg }} == 'other'* ]]; then
            NOTE="Others"
          fi

          echo ${{ steps.commit-message.outputs.commit_msg }}
          echo $NOTE

      - name: Push tag to GitHub
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git config --global push.followTags true
          NEW_TAG=${{ steps.bump.outputs.new_tag }}
          git tag {{ steps.bump.outputs.new_tag }}
          echo "New Tag: $NEW_TAG"
          git push origin $NEW_TAG
          echo "New bump part: ${{ steps.bump.outputs.part }}"
          TAG=${{ steps.bump.outputs.new_tag }}
          echo "New tag: $TAG"

      - name: Publish go-pkg
        run: |
          PKG="github.com/wednesday-solutions/negt@$TAG"
          echo "New package version: $PKG"
          GOPROXY=proxy.golang.org go list -m $PKG

      - name: Release go-pkg
        uses: anton-yurchenko/git-release@main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/*.zip
          RELEASE_NAME: $NOTE
